import StandardAndPremiumSeatLayout from "../StandardAndPremiumSeatLayout";
import { useParams } from "react-router-dom";
import { v4 as uuid } from "uuid";

import "./index.css";

const initialLeftSideSeatLayoutList = [
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
];
const initialRightSideSeatLayoutList = [
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
];
const initialCenterSideSeatLayoutList = [
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
];
const initialPremiumSeatLayoutList = [
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
  { id: uuid(), availability: true },
];

const StandardSeatsLayoutObj = {
  leftSideSeatLayout: initialLeftSideSeatLayoutList,
  centerSeatLayoutList: initialCenterSideSeatLayoutList,
  rightSideSeatLayout: initialRightSideSeatLayoutList,
};

const SeatBookingPage = () => {
  const { movieName } = useParams();

  const standardSeatsLayout = JSON.parse(
    localStorage.getItem(`standardLayout${movieName}`)
  );
  const premiumSeatsLayout = JSON.parse(
    localStorage.getItem(`premiumLayout${movieName}`)
  );
  if (standardSeatsLayout === null) {
    localStorage.setItem(
      `standardLayout${movieName}`,
      JSON.stringify(StandardSeatsLayoutObj)
    );
  }
  if (premiumSeatsLayout === null) {
    localStorage.setItem(
      `premiumLayout${movieName}`,
      JSON.stringify({ premiumSeatLayoutList: initialPremiumSeatLayoutList })
    );
  }

  return <StandardAndPremiumSeatLayout movieName={movieName} />;
};

export default SeatBookingPage;
